export default {
  "login": "urvashi-code1255",
  "id": 63122133,
  "node_id": "MDQ6VXNlcjYzMTIyMTMz",
  "avatar_url": "https://avatars2.githubusercontent.com/u/63122133?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/urvashi-code1255",
  "html_url": "https://github.com/urvashi-code1255",
  "followers_url": "https://api.github.com/users/urvashi-code1255/followers",
  "following_url": "https://api.github.com/users/urvashi-code1255/following{/other_user}",
  "gists_url": "https://api.github.com/users/urvashi-code1255/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/urvashi-code1255/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/urvashi-code1255/subscriptions",
  "organizations_url": "https://api.github.com/users/urvashi-code1255/orgs",
  "repos_url": "https://api.github.com/users/urvashi-code1255/repos",
  "events_url": "https://api.github.com/users/urvashi-code1255/events{/privacy}",
  "received_events_url": "https://api.github.com/users/urvashi-code1255/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Urvashi Anand",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Making my own way 🎯",
  "twitter_username": null,
  "public_repos": 31,
  "public_gists": 0,
  "followers": 15,
  "following": 40,
  "created_at": "2020-04-03T18:40:54Z",
  "updated_at": "2020-12-26T05:31:25Z"
};
